
/////////////////////////////////////////////////////////////////////////////////////////////
// gapidevcaps.h
//
// Renderer interface device caps structures 
/////////////////////////////////////////////////////////////////////////////////////////////
enum GAPIDEVCAPSPARAM
{
    GAPI_DEVPARAM_MULTISAMPLE_SAMPLES,
    GAPI_DEVPARAM_VERTICAL_SYNC,
    GAPI_DEVPARAM_VERTICAL_SYNC_TEAR,

    GAPI_DEVPARAM_MAX_LIGHTS,
    GAPI_DEVPARAM_MAX_TEXTURE_SIZE,
    GAPI_DEVPARAM_MAX_TEXTURE_UNITS,
    GAPI_DEVPARAM_MAX_TEXTURE_ANISOTROPY,

    GAPI_DEVPARAM_MIN_POINT_SIZE,
    GAPI_DEVPARAM_MAX_POINT_SIZE,

    // Vertex Shader Params
    GAPI_DEVPARAM_VERTEX_SHADER,
    GAPI_DEVPARAM_MAX_VERTEX_ATTRIBS,
    GAPI_DEVPARAM_MAX_VERTEX_UNIFORM_COMPONENTS,
    GAPI_DEVPARAM_MAX_VERTEX_VARYING_COMPONENTS,
    GAPI_DEVPARAM_MAX_VARYING_COMPONENTS,
    GAPI_DEVPARAM_MAX_VERTEX_TEXTURE_UNITS,
    GAPI_DEVPARAM_MAX_VARYING_FLOATS,
    GAPI_DEVPARAM_MAX_COMBINED_TEXTURE_UNITS,

    // Fragment Shader Params
    GAPI_DEVPARAM_PIXEL_SHADER,
    GAPI_DEVPARAM_MAX_FRAGMENT_UNIFORM_COMPONENTS,
    GAPI_DEVPARAM_MAX_FRAGMENT_TEXTURE_UNITS,

    // Geometry Shader Params
    GAPI_DEVPARAM_GEOMETRY_SHADER,
    GAPI_DEVPARAM_MAX_GEOMETRY_OUTPUT_VERT,
    GAPI_DEVPARAM_MAX_GEOMETRY_TEXTURE_UNITS,
    GAPI_DEVPARAM_MAX_GEOMETRY_VARYING_COMPONENTS,
    GAPI_DEVPARAM_MAX_GEOMETRY_UNIFORM_COMPONENTS,
    GAPI_DEVPARAM_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS,

    // Uniform Blocks Params
    GAPI_DEVPARAM_UNIFORM_BLOCKS,
    GAPI_DEVPARAM_MAX_VERTEX_UNIFORM_BLOCKS,
    GAPI_DEVPARAM_MAX_GEOMETRY_UNIFORM_BLOCKS,
    GAPI_DEVPARAM_MAX_FRAGMENT_UNIFORM_BLOCKS,
    GAPI_DEVPARAM_MAX_COMBINED_UNIFORM_BLOCKS,
    GAPI_DEVPARAM_MAX_UNIFORM_BUFFER_BINDINGS,
    GAPI_DEVPARAM_MAX_UNIFORM_BLOCK_SIZE,
    GAPI_DEVPARAM_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS,
    GAPI_DEVPARAM_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS,
    GAPI_DEVPARAM_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS,

    // Draw Buffers Params
    GAPI_DEVPARAM_MAX_DRAW_BUFFERS,

    // Clip Distances
    GAPI_DEVPARAM_MAX_CLIP_DISTANCES,

    // Transform Feedback
    GAPI_DEVPARAM_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS,
    GAPI_DEVPARAM_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS,
    GAPI_DEVPARAM_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS,

    // Blend Func Extended
    GAPI_DEVPARAM_MAX_DUAL_SOURCE_DRAW_BUFFERS,

    // Texture Layers
    GAPI_DEVPARAM_MAX_ARRAY_TEXTURE_LAYERS,
    GAPI_DEVPARAM_MIN_PROGRAM_TEXEL_OFFSET,
    GAPI_DEVPARAM_MAX_PROGRAM_TEXEL_OFFSET,

    // Texture Rectangle
    GAPI_DEVPARAM_MAX_RECTANGLE_TEXTURE_SIZE,

    // Program Texture
    GAPI_DEVPARAM_MIN_SAMPLE_SHADING_VALUE,
    GAPI_DEVPARAM_MIN_PROGRAM_TEXTURE_GATHER_OFFSET,
    GAPI_DEVPARAM_MAX_PROGRAM_TEXTURE_GATHER_OFFSET,
    GAPI_DEVPARAM_MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS,

    // Texture Cube Map
    GAPI_DEVPARAM_MAX_CUBE_MAP_TEXTURE_SIZE,

    // Framebuffer Object
    GAPI_DEVPARAM_MAX_RENDERBUFFER_SIZE,
    GAPI_DEVPARAM_MAX_COLOR_ATTACHMENTS,
    GAPI_DEVPARAM_MAX_SAMPLES,

    // Texture Buffer Object
    GAPI_DEVPARAM_MAX_TEXTURE_BUFFER_SIZE,

    // Texture Multisample
    GAPI_DEVPARAM_MAX_SAMPLE_MASK_WORDS,
    GAPI_DEVPARAM_MAX_COLOR_TEXTURE_SAMPLES,
    GAPI_DEVPARAM_MAX_DEPTH_TEXTURE_SAMPLES,
    GAPI_DEVPARAM_MAX_INTEGER_SAMPLES,

    // GPU Shader5
    GAPI_DEVPARAM_MAX_GEOMETRY_SHADER_INVOCATIONS,
    GAPI_DEVPARAM_MIN_FRAGMENT_INTERPOLATION_OFFSET,
    GAPI_DEVPARAM_MAX_FRAGMENT_INTERPOLATION_OFFSET,
    GAPI_DEVPARAM_FRAGMENT_INTERPOLATION_OFFSET_BITS,
    
    // Tessellation Shader
    GAPI_DEVPARAM_MAX_PATCH_VERTICES, 
    GAPI_DEVPARAM_MAX_TESS_GEN_LEVEL,            
    GAPI_DEVPARAM_MAX_TESS_CONTROL_UNIFORM_COMPONENTS,
    GAPI_DEVPARAM_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS,
    GAPI_DEVPARAM_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS,
    GAPI_DEVPARAM_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS,
    GAPI_DEVPARAM_MAX_TESS_CONTROL_OUTPUT_COMPONENTS,
    GAPI_DEVPARAM_MAX_TESS_PATCH_COMPONENTS,
    GAPI_DEVPARAM_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS,
    GAPI_DEVPARAM_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS,
    GAPI_DEVPARAM_MAX_TESS_CONTROL_UNIFORM_BLOCKS,
    GAPI_DEVPARAM_MAX_TESS_EVALUATION_UNIFORM_BLOCKS,
    GAPI_DEVPARAM_MAX_TESS_CONTROL_INPUT_COMPONENTS,
    GAPI_DEVPARAM_MAX_TESS_EVALUATION_INPUT_COMPONENTS,
    GAPI_DEVPARAM_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS,
    GAPI_DEVPARAM_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS,

    // Transform Feedback3
    GAPI_DEVPARAM_MAX_TRANSFORM_FEEDBACK_BUFFERS,
    GAPI_DEVPARAM_MAX_VERTEX_STREAMS,

    // Viewport Array
    GAPI_DEVPARAM_MAX_VIEWPORTS,

    // Debug Output
    GAPI_DEVPARAM_MAX_DEBUG_MESSAGE_LENGTH,
    GAPI_DEVPARAM_MAX_DEBUG_LOGGED_MESSAGES,

    // Map Buffer Alignment
    GAPI_DEVPARAM_MIN_MAP_BUFFER_ALIGNMENT,

    // Shader Atomic Counters
    GAPI_DEVPARAM_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS,
    GAPI_DEVPARAM_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS,
    GAPI_DEVPARAM_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS,
    GAPI_DEVPARAM_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS,
    GAPI_DEVPARAM_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS,
    GAPI_DEVPARAM_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS,
    GAPI_DEVPARAM_MAX_VERTEX_ATOMIC_COUNTERS,
    GAPI_DEVPARAM_MAX_TESS_CONTROL_ATOMIC_COUNTERS,
    GAPI_DEVPARAM_MAX_TESS_EVALUATION_ATOMIC_COUNTERS,
    GAPI_DEVPARAM_MAX_GEOMETRY_ATOMIC_COUNTERS,
    GAPI_DEVPARAM_MAX_FRAGMENT_ATOMIC_COUNTERS,
    GAPI_DEVPARAM_MAX_COMBINED_ATOMIC_COUNTERS,
    GAPI_DEVPARAM_MAX_ATOMIC_COUNTER_BUFFER_SIZE,
    GAPI_DEVPARAM_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS,

    // Shader Image Load Store
    GAPI_DEVPARAM_MAX_IMAGE_UNITS,
    GAPI_DEVPARAM_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS,

    GAPI_DEVPARAM_MAX_IMAGE_SAMPLES,
    GAPI_DEVPARAM_MAX_VERTEX_IMAGE_UNIFORMS,
    GAPI_DEVPARAM_MAX_TESS_CONTROL_IMAGE_UNIFORMS,
    GAPI_DEVPARAM_MAX_TESS_EVALUATION_IMAGE_UNIFORMS,
    GAPI_DEVPARAM_MAX_GEOMETRY_IMAGE_UNIFORMS,
    GAPI_DEVPARAM_MAX_FRAGMENT_IMAGE_UNIFORMS,
    GAPI_DEVPARAM_MAX_COMBINED_IMAGE_UNIFORMS,
    
};

#define GAPI_COORD_UPPER_LEFT 0
#define GAPI_COORD_LOWER_LEFT 1

#define GAPI_TEX_GENMIPMAPS_FLAG    0x1
#define GAPI_TEX_WORD_ALIGN_FLAG    0x2
#define GAPI_TEX_DWORD_ALIGN_FLAG   0x4
#define GAPI_TEX_CUBE_MAP_FLAG      0x8
#define GAPI_TEX_RECT_FLAG          0x10
#define GAPI_TEX_RENDER_TARGET_FLAG 0x20
#define GAPI_TEX_ARRAY_FLAG         0x40

#define GAPI_PARAMS_QUERY_FLAG      0x1


/*
enum GAPIDEVCAPSPARAM
{
GAPI_DEVPARAM_COLOR_BUFFER_FLOAT,
GAPI_DEVPARAM_DEPTH_BUFFER_FLOAT,
GAPI_DEVPARAM_HALF_FLOAT_PIXEL,
GAPI_DEVPARAM_HALF_FLOAT_VERTEX,
GAPI_DEVPARAM_POINT_SPRITE,
GAPI_DEVPARAM_TEXTURE_FLOAT,
GAPI_DEVPARAM_TEXTURE_NON_POWER_OF_TWO,
GAPI_DEVPARAM_TEXTURE_RECTANGLE,
GAPI_DEVPARAM_TEXTURE_3D,
GAPI_DEVPARAM_SEPARATE_STENCIL,
GAPI_DEVPARAM_STENCIL_TWO_SIDE,
GAPI_DEVPARAM_BLEND_EQUATION_SEPARATE,
GAPI_DEVPARAM_BLEND_FUNC_SEPARATE,
GAPI_DEVPARAM_BLEND_MINMAX,
GAPI_DEVPARAM_BLEND_COLOR,
GAPI_DEVPARAM_OCCLUSION_QUERY,
GAPI_DEVPARAM_TEXTURE_MIRROR_REPEAT,
GAPI_DEVPARAM_TEXTURE_MIRROR_ONCE,
GAPI_DEVPARAM_TEXTURE_BORDER_CLAMP,
GAPI_DEVPARAM_ABGR,
GAPI_DEVPARAM_BGRA,
GAPI_DEVPARAM_SECONDARY_COLOR,
GAPI_DEVPARAM_TEXTURE_MIRROR_CLAMP,
GAPI_DEVPARAM_TEXTURE_COMPRESSION_3DC,
GAPI_DEVPARAM_TEXTURE_COMPRESSION_S3TC,

GAPI_DEVPARAM_MULTISAMPLE,

GAPI_DEVPARAM_MAX_TEXTURE_SIZE,
GAPI_DEVPARAM_MAX_TEXTURE_UNITS,
GAPI_DEVPARAM_MAX_TEXTURE_ANISOTROPY,

GAPI_DEVPARAM_MIN_POINT_SIZE,
GAPI_DEVPARAM_MAX_POINT_SIZE,

GAPI_DEVPARAM_MAX_VERTEX_ATTRIBS,
GAPI_DEVPARAM_MAX_FRAGMENT_UNIFORM_COMPONENTS,
GAPI_DEVPARAM_MAX_VERTEX_UNIFORM_COMPONENTS,
GAPI_DEVPARAM_MAX_VERTEX_VARYING_COMPONENTS,
GAPI_DEVPARAM_MAX_VARYING_COMPONENTS,
GAPI_DEVPARAM_MAX_VERTEX_TEXTURE_UNITS,
GAPI_DEVPARAM_MAX_VARYING_FLOATS,

GAPI_DEVPARAM_GEOMETRY_SHADER,
GAPI_DEVPARAM_MAX_GEOMETRY_OUTPUT_VERT,
GAPI_DEVPARAM_MAX_GEOMETRY_TEXTURE_UNITS,
GAPI_DEVPARAM_MAX_GEOMETRY_VARYING_COMPONENTS,
GAPI_DEVPARAM_MAX_GEOMETRY_UNIFORM_COMPONENTS,
GAPI_DEVPARAM_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS,

};
*/
